name: "Test Dockerfile structure"
on: pull_request

jobs:
  dockerfile-php-only-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
      - name: checkout source
        uses: actions/checkout@master
      - name: Install Google Container Structure Test Framework
        run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - name: Build docker images PHP Only
        run: docker build -t antistatique/php-dev:${{ matrix.php_version }} -f ./php/${{ matrix.php_version }}/Dockerfile .
      - name: Run tests PHP only
        run: container-structure-test test --image antistatique/php-dev:${{ matrix.php_version }} --config ./php/tests/baseMetadataTests.yaml --config ./php/tests/baseFileExistenceTests.yaml --config ./php/${{ matrix.php_version }}/tests/config--${{ matrix.php_version }}.yaml


  dockerfile-php-node-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
        node_version: ['8', '10', '11', '12']
        exclude:
          - php_version: '5.6'
            node_version: 10
          - php_version: '5.6'
            node_version: 11
          - php_version: '5.6'
            node_version: 12
          - php_version: '7.0'
            node_version: 11
          - php_version: '7.0'
            node_version: 12
          - php_version: '7.3'
            node_version: 8
          - php_version: '7.4'
            node_version: 8
          - php_version: '8.0'
            node_version: 8
          - php_version: '8.0'
            node_version: 10
          - php_version: '8.0'
            node_version: 11
        include:
          - node_version: 6
            php_version: '7.1'
          - node_version: 9
            php_version: '7.1'
          - node_version: 9
            php_version: '7.2'
          - node_version: 14
            php_version: '8.0'

    steps:
      - name: checkout source
        uses: actions/checkout@master
      - name: Install Google Container Structure Test Framework
        run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - name: Build docker images PHP-Node
        run: docker build -t antistatique/php-dev:${{ matrix.php_version }}-node${{ matrix.node_version }} -f ./php/${{ matrix.php_version }}/node/${{ matrix.node_version }}/Dockerfile .
      - name: Run tests PHP-Node
        run: container-structure-test test --image antistatique/php-dev:${{ matrix.php_version }}-node${{ matrix.node_version }} --config ./php/tests/baseMetadataTests.yaml --config ./php/tests/baseFileExistenceTests.yaml --config ./php/${{ matrix.php_version }}/tests/config--${{ matrix.php_version }}-node${{ matrix.node_version }}.yaml
